from __future__ import annotations

from time import perf_counter

import torch
import triton
import triton.language as tl

from llvq_implicit import DIM, ImplicitShellDatabase


@triton.jit
def _score_min_kernel(
    x_ptr,
    cand_ptr,
    out_score_ptr,
    out_index_ptr,
    n_candidates,
    base_index,
    mode: tl.constexpr,
    dim: tl.constexpr,
    BLOCK_N: tl.constexpr,
):
    batch_id = tl.program_id(0)
    block_id = tl.program_id(1)
    offsets = block_id * BLOCK_N + tl.arange(0, BLOCK_N)
    mask = offsets < n_candidates

    scores = tl.zeros((BLOCK_N,), dtype=tl.float32)
    dot = tl.zeros((BLOCK_N,), dtype=tl.float32)
    cand_norm2 = tl.zeros((BLOCK_N,), dtype=tl.float32)
    x_norm2 = tl.full((), 0.0, dtype=tl.float32)

    for d in tl.static_range(0, dim):
        x_val = tl.load(x_ptr + batch_id * dim + d).to(tl.float32)
        cand_val = tl.load(cand_ptr + offsets * dim + d, mask=mask, other=0.0).to(tl.float32)

        if mode == 0:
            diff = x_val - cand_val
            scores += diff * diff
        else:
            dot += x_val * cand_val
            cand_norm2 += cand_val * cand_val
            x_norm2 += x_val * x_val

    if mode == 1:
        denom = tl.sqrt(x_norm2 * cand_norm2)
        cosine = dot / tl.maximum(denom, 1.0e-12)
        scores = 1.0 - cosine

    scores = tl.where(mask, scores, float("inf"))
    best_score = tl.min(scores, axis=0)
    best_offset = tl.argmin(scores, axis=0)
    out_pos = batch_id * tl.num_programs(1) + block_id
    tl.store(out_score_ptr + out_pos, best_score)
    tl.store(out_index_ptr + out_pos, best_offset + base_index)


class LLVQTritonSearch:
    """
    Experimental Triton search over implicit LLVQ candidates.

    The candidate set is still generated by `ImplicitShellDatabase` in chunks, but
    each chunk is scored and reduced by a custom GPU kernel instead of materializing
    a full `(batch, candidates)` score matrix.
    """

    def __init__(
        self,
        shell_db: ImplicitShellDatabase,
        search_chunk_size: int = 65_536,
        block_n: int = 256,
    ):
        if shell_db.total_count == 0:
            raise ValueError("shell_db is empty; call build(...) first")
        if not torch.cuda.is_available() or shell_db.device.type != "cuda":
            raise ValueError("LLVQTritonSearch requires a CUDA device")
        self.db = shell_db
        self.search_chunk_size = search_chunk_size
        self.block_n = triton.next_power_of_2(block_n)

    def quantize(
        self,
        x: torch.Tensor,
        mode: str = "euclidean",
        return_vectors: bool = True,
        verbose: bool = False,
        progress_every: int = 1_000_000,
    ):
        if mode not in {"euclidean", "angular"}:
            raise ValueError(f"unknown quantization mode: {mode}")

        x = torch.as_tensor(x, dtype=self.db.dtype, device=self.db.device).contiguous()
        single = x.ndim == 1
        x = x.reshape(-1, DIM).contiguous()

        best_scores = torch.full((x.shape[0],), torch.inf, dtype=torch.float32, device=self.db.device)
        best_indices = torch.zeros((x.shape[0],), dtype=torch.long, device=self.db.device)
        mode_id = 0 if mode == "euclidean" else 1

        seen = 0
        next_report = progress_every
        total = self.db.total_count

        if verbose:
            print(
                f"triton quantizing {x.shape[0]} vector(s) over {total} implicit candidates "
                f"(mode={mode}, chunk_size={self.search_chunk_size}, block_n={self.block_n})",
                flush=True,
            )

        for base_idx, candidates in self.db.iter_candidate_chunks(self.search_chunk_size):
            candidates = candidates.to(device=self.db.device, dtype=self.db.dtype).contiguous()
            n_candidates = candidates.shape[0]
            n_blocks = triton.cdiv(n_candidates, self.block_n)
            block_scores = torch.empty((x.shape[0], n_blocks), dtype=torch.float32, device=self.db.device)
            block_indices = torch.empty((x.shape[0], n_blocks), dtype=torch.long, device=self.db.device)

            _score_min_kernel[(x.shape[0], n_blocks)](
                x,
                candidates,
                block_scores,
                block_indices,
                n_candidates,
                base_idx,
                mode_id,
                DIM,
                BLOCK_N=self.block_n,
            )

            chunk_scores, local_block = block_scores.min(dim=1)
            chunk_indices = block_indices.gather(1, local_block[:, None]).squeeze(1)
            improved = chunk_scores < best_scores
            best_scores[improved] = chunk_scores[improved]
            best_indices[improved] = chunk_indices[improved]

            seen += n_candidates
            if verbose and (seen >= next_report or seen == total):
                pct = 100.0 * seen / total
                print(
                    f"  scored {seen:12d}/{total} candidates ({pct:6.2f}%) | "
                    f"best_score={best_scores.min().item():.6g}",
                    flush=True,
                )
                while next_report <= seen:
                    next_report += progress_every

        vectors = self.dequantize(best_indices) if return_vectors else None
        if single:
            best_indices = best_indices[0]
            best_scores = best_scores[0]
            vectors = vectors[0] if vectors is not None else None
        return best_indices, vectors, best_scores

    def dequantize(self, idx: int | torch.Tensor) -> torch.Tensor:
        return self.db.dequantize(idx)


def demo(
    M: int = 5,
    max_coord: int = 2,
    batch_vectors: int = 2,
    input_scale: float = 3.0,
    mode: str = "euclidean",
    search_chunk_size: int = 65_536,
    block_n: int = 256,
    progress_every: int = 1_000_000,
    verbose: bool = True,
) -> None:
    db = ImplicitShellDatabase(device="cuda")
    db.build(M=M, max_coord=max_coord, verbose=verbose)
    print("device:", db.device)
    print("shell sizes:", db.shell_sizes())
    print("total implicit vectors:", db.total_count)

    quantizer = LLVQTritonSearch(db, search_chunk_size=search_chunk_size, block_n=block_n)
    x = torch.randn(batch_vectors, DIM, device=db.device) * input_scale

    torch.cuda.synchronize()
    quantize_start = perf_counter()
    idx, recon, scores = quantizer.quantize(
        x,
        mode=mode,
        verbose=verbose,
        progress_every=progress_every,
    )
    torch.cuda.synchronize()
    quantize_seconds = perf_counter() - quantize_start

    torch.cuda.synchronize()
    dequantize_start = perf_counter()
    timed_recon = quantizer.dequantize(idx)
    torch.cuda.synchronize()
    dequantize_seconds = perf_counter() - dequantize_start

    diff = x - recon
    print(f"quantize time: {quantize_seconds:.6f}s")
    print(f"dequantize time: {dequantize_seconds:.6f}s")
    print("timed dequantize matches:", torch.equal(recon, timed_recon))
    print("indices:", idx)
    print("scores:", scores)
    print("x:", x)
    print("recon:", recon)
    print("x - recon:", diff)
    print("per-vector l2 error:", diff.norm(dim=1))
    print("mean squared error:", diff.square().mean())


def _argparse_main() -> None:
    import argparse

    parser = argparse.ArgumentParser(description="Triton kernel LLVQ implicit search demo")
    parser.add_argument("--M", type=int, default=5)
    parser.add_argument("--max_coord", type=int, default=2)
    parser.add_argument("--batch_vectors", type=int, default=2)
    parser.add_argument("--input_scale", type=float, default=3.0)
    parser.add_argument("--mode", choices=["euclidean", "angular"], default="euclidean")
    parser.add_argument("--search_chunk_size", type=int, default=65_536)
    parser.add_argument("--block_n", type=int, default=256)
    parser.add_argument("--progress_every", type=int, default=1_000_000)
    parser.add_argument("--quiet", action="store_true")
    args = parser.parse_args()

    demo(
        M=args.M,
        max_coord=args.max_coord,
        batch_vectors=args.batch_vectors,
        input_scale=args.input_scale,
        mode=args.mode,
        search_chunk_size=args.search_chunk_size,
        block_n=args.block_n,
        progress_every=args.progress_every,
        verbose=not args.quiet,
    )


if __name__ == "__main__":
    try:
        import fire
    except ImportError:
        _argparse_main()
    else:
        fire.Fire(demo)
